Global:
  InitCPIO: true
  InitCPIOHookDirs:
    - /build/initcpio
    - /usr/lib/initcpio
  PostHooksDir: /build/posthooks
Components:
  Enabled: false
EFI:
  Enabled: true
  Versions: false
Kernel:
  Prefix: zfsbootmenu
  CommandLine: "zfsbootmenu ro quiet loglevel=0 nomodeset zbm.timeout=20 ip=:::::eth0:dhcp"
