Global:
  InitCPIO: true
  InitCPIOHookDirs:
    - /build/initcpio
    - /usr/lib/initcpio
Components:
  Enabled: false
EFI:
  Enabled: true
  Versions: false
Kernel:
  Prefix: zfsbootmenu
  CommandLine: zfsbootmenu ro quiet loglevel=0 nomodeset
